services:
  postgres:
    image: postgres:16
    container_name: scorecard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scorecard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  scorecard-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scorecard-api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/scorecard
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data: 